#Mouse config ---------------------
# CONFIG_PMW3610_INVERT_X=y
# CONFIG_PMW3610_INVERT_Y=y
# CONFIG_PMW3610_SWAP_XY=y
# CONFIG_PMW3610_REPORT_INTERVAL_MIN=12
# CONFIG_PMW3610_LOG_LEVEL_DBG=y
# CONFIG_PMW3610_INIT_POWER_UP_EXTRA_DELAY_MS=300 // <--see Troubleshooting

#Encoder config -------------------
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

#Battery config -------------------
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

#Layer LED config -------------------
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=30
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10
CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y
# Layer 0 (Win Default): 消灯（未設定＝デフォルト）
# Layer 1 (Symbol): 黄
CONFIG_RGBLED_WIDGET_LAYER_1_COLOR=3
# Layer 2 (Number/Fn): 青
CONFIG_RGBLED_WIDGET_LAYER_2_COLOR=4
# Layer 3 (Nav Win): シアン
CONFIG_RGBLED_WIDGET_LAYER_3_COLOR=6
# Layer 4 (BT): 赤
CONFIG_RGBLED_WIDGET_LAYER_4_COLOR=1
# Layer 5 (Mouse): マゼンタ
CONFIG_RGBLED_WIDGET_LAYER_5_COLOR=5
# Layer 6 (Scroll): 白
CONFIG_RGBLED_WIDGET_LAYER_6_COLOR=7
# Layer 10 (Mac Default): 緑
CONFIG_RGBLED_WIDGET_LAYER_10_COLOR=2
# Layer 11 (Nav Mac): シアン
CONFIG_RGBLED_WIDGET_LAYER_11_COLOR=6

#ZMK Studio config -------------------
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

#Bluetooth config -------------------
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12


CONFIG_ZMK_POINTING=y

CONFIG_ZMK_BEHAVIOR_OS_LAYER=y
