#Mouse config ---------------------
# CONFIG_PMW3610_INVERT_X=y
# CONFIG_PMW3610_INVERT_Y=y
# CONFIG_PMW3610_SWAP_XY=y
# CONFIG_PMW3610_REPORT_INTERVAL_MIN=12
# CONFIG_PMW3610_LOG_LEVEL_DBG=y
# CONFIG_PMW3610_INIT_POWER_UP_EXTRA_DELAY_MS=300 // <--see Troubleshooting

#Encoder config -------------------
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

#Battery config -------------------
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

#Layer LED config -------------------
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=30
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10
CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y
# L0 (default_win): 🔵 青 ← Winモード
CONFIG_RGBLED_WIDGET_LAYER_0_COLOR=4
# L1 (default_mac): 🟢 緑 ← Macモード
CONFIG_RGBLED_WIDGET_LAYER_1_COLOR=2
# L2 (symbol): 🟡 黄
CONFIG_RGBLED_WIDGET_LAYER_2_COLOR=3
# L3 (num_fn): 🔴 赤
CONFIG_RGBLED_WIDGET_LAYER_3_COLOR=1
# L4 (nav_win): 🩵 シアン
CONFIG_RGBLED_WIDGET_LAYER_4_COLOR=6
# L5 (nav_mac): 🩵 シアン
CONFIG_RGBLED_WIDGET_LAYER_5_COLOR=6
# L6 (mouse): 消灯
CONFIG_RGBLED_WIDGET_LAYER_6_COLOR=0
# L7 (scroll): 消灯
CONFIG_RGBLED_WIDGET_LAYER_7_COLOR=0
# L8 (gesture_browser_win): ◯ 白
CONFIG_RGBLED_WIDGET_LAYER_8_COLOR=7
# L9 (gesture_browser_mac): ◯ 白
CONFIG_RGBLED_WIDGET_LAYER_9_COLOR=7
# L10 (gesture_vdesk_win): ◯ 白
CONFIG_RGBLED_WIDGET_LAYER_10_COLOR=7
# L11 (gesture_vdesk_mac): ◯ 白
CONFIG_RGBLED_WIDGET_LAYER_11_COLOR=7
# L12 (gesture_general_win): ◯ 白
CONFIG_RGBLED_WIDGET_LAYER_12_COLOR=7
# L13 (gesture_general_mac): ◯ 白
CONFIG_RGBLED_WIDGET_LAYER_13_COLOR=7
# L14 (app_switch): ◯ 白
CONFIG_RGBLED_WIDGET_LAYER_14_COLOR=7
# L15 (bt): 🟣 マゼンタ ← MacモードのL1より高いBT/Systemレイヤー
CONFIG_RGBLED_WIDGET_LAYER_15_COLOR=5

#ZMK Studio config -------------------
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

#Bluetooth config -------------------
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12


CONFIG_ZMK_POINTING=y

CONFIG_ZMK_BEHAVIOR_OS_LAYER=y
