name: Draw ZMK keymaps

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "config/mona2.keymap"
      - "config/**/*.dtsi"
      - ".keymap-drawer.yaml"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/mona2.keymap"
      config_path: ".keymap-drawer.yaml"
      output_folder: "."
